import cron from "node-cron";
import AutoGeneratedPlaylist from "../model/autoGeneratedPlaylist";
import Audio from "../model/audio";

// cron.schedule("*/2 * * * * *", () => {
//   console.log("I am running!");
// });

const generatedPlaylist = async () => {
  const result = await Audio.aggregate([
    { $sort: { likes: -1 } },
    {
      $sample: { size: 20 },
    },
    {
      $group: {
        _id: "$category",
        audios: { $push: "$$ROOT._id" },
      },
    },
  ]);
  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      {
        title: item._id,
      },
      { $set: { items: item.audios } },
      {
        upsert: true,
      }
    );
  });
};

cron.schedule("0 0 * * * ", async () => {
  //this will run on every 24 hrs
  await generatedPlaylist();
});
